### PR TITLE
Allow specification of the local network interface for HTTP requests. Fixes #1389.

### LINKED ISSUE #1389: Possibility to specify interface/IP for outgoing (HTTP) connections.
We need something like curl --interface option:
> --interface [name]
> Perform an operation using a specified interface. You can enter interface name, IP address or host name. An example could look like:
> curl --interface eth0:1 http://www.netscape.com/`

And we are willing to pay for it.

### PR DESCRIPTION
**Pull request by s-ludwig**
This adds `HTTPClientSettings.networkInterface` and a `bind_address` parameter for `connectTCP`. See #1389.

### CODE REVIEW

**Comment by s-ludwig** [comment]
@japplegame: Merging this now. I'll create an alpha tag afterwards for testing. Let me know if anything is missing.

**Comment by japplegame** [comment]
Thanks. I'll test it soon.

**Comment by japplegame** [comment]
I started testing this on our high load beta-server. vibe.d 0.7.28 + this PR.
Lets wait a few days.

**Comment by etcimon** [comment]
Does this actually work for libasync? It looks like tcp.ip is replaced by the tcp.peer assignment. I don't think there's any underlying support for this yet

**Comment by etcimon** [comment]
Looks like a one-liner

https://idea.popcount.org/2014-04-03-bind-before-connect/

**Comment by etcimon** [comment]
It's likely to throw on EADDRINUSE when the port is specified, should be important to document it

**Comment by japplegame** [comment]
After about 30 minutes the server crashed.
I'm not sure that this PR is the reason, but so far I am unable to test it.
At the moment our production server runs on vibe.d 0.7.26. This version is stable enough.

Core dump backtrace:
```
#0  0x0000000000acff58 in rt.deh_win64_posix.terminate() ()
#1  0x0000000000a75078 in _d_throwc ()
#2  0x0000000000a6dc4a in _d_assert_msg ()
#3  0x00000000009d67d0 in vibe.core.core.VibeDriverCore.resumeCoreTask() (this=0x7fce99995900, event_exception=0x0, ctask=0x7fce46006600) at ../forks/vibe.d-0.7.28/source/vibe/core/core.d:1239
#4  0x00000000009d66b2 in vibe.core.core.VibeDriverCore.resumeTask() (this=0x7fce99995900, initial_resume=false, event_exception=0x0, task=...) at ../forks/vibe.d-0.7.28/source/vibe/core/core.d:1232
#5  0x00000000009d641c in vibe.core.core.VibeDriverCore.resumeTask() (this=0x7fce99995900, event_exception=0x0, task=...) at ../forks/vibe.d-0.7.28/source/vibe/core/core.d:1208
#6  0x00000000009da759 in vibe.core.drivers.libevent2.Libevent2Driver.processTimers() (this=0x7ffefd9e52b8, data=..., periodic=false, timer=56540) at ../forks/vibe.d-0.7.28/source/vibe/core/drivers/libevent2.d:488
#7  0x00000000009e53fb in vibe.core.drivers.timerqueue.__T10TimerQueueTS4vibe4core7drivers9libevent29TimerInfoVli10000Z.TimerQueue.consumeTimeouts() (this=..., del=..., now=...)
    at ../forks/vibe.d-0.7.28/source/vibe/core/drivers/timerqueue.d:107
#8  0x00000000009da670 in vibe.core.drivers.libevent2.Libevent2Driver.processTimers() (this=0x7fce99994500) at ../forks/vibe.d-0.7.28/source/vibe/core/drivers/libevent2.d:480
#9  0x00000000009da996 in vibe.core.drivers.libevent2.Libevent2Driver.onTimerTimeout() (_param_0=-1, events=1, userptr=0x7fce99994500) at ../forks/vibe.d-0.7.28/source/vibe/core/drivers/libevent2.d:518
#10 0x00007fce99450a14 in event_base_loop () from /lib64/libevent-2.0.so.5
#11 0x00000000009d8aff in vibe.core.drivers.libevent2.Libevent2Driver.processEvents() (this=0x7fce99994500) at ../forks/vibe.d-0.7.28/source/vibe/core/drivers/libevent2.d:215
#12 0x00000000009d6aa0 in vibe.core.core.VibeDriverCore.notifyIdle() (this=0x7fce99995900) at ../forks/vibe.d-0.7.28/source/vibe/core/core.d:1277
#13 0x00000000009d89a3 in vibe.core.drivers.libevent2.Libevent2Driver.runEventLoop() (this=0x7fce99994500) at ../forks/vibe.d-0.7.28/source/vibe/core/drivers/libevent2.d:198
#14 0x00000000009d468a in vibe.core.core.runEventLoop() () at ../forks/vibe.d-0.7.28/source/vibe/core/core.d:97
#15 0x0000000000911551 in application.ApplicationImpl.__T3runS29_D10dispatcher10__lambda21FZvZ.run() (this=0x7fce9999d940) at libs/misc/source/application.d:120
#16 0x0000000000906d4b in D main () at libs/misc/source/application.d:139
#17 0x0000000000a755c3 in rt.dmain2._d_run_main() ()
#18 0x0000000000a75519 in rt.dmain2._d_run_main() ()
#19 0x0000000000a7557f in rt.dmain2._d_run_main() ()
#20 0x0000000000a75519 in rt.dmain2._d_run_main() ()
#21 0x0000000000a75476 in _d_run_main ()
#22 0x000000000091fb10 in main ()
```

**Comment by japplegame** [comment]
command used for patching:
```
git checkout tags/v.0.7.28
patch -p1 < 1407.diff
```
where 1407.diff is https://patch-diff.githubusercontent.com/raw/rejectedsoftware/vibe.d/pull/1407.diff

**Comment by s-ludwig** [comment]
If you were running on 0.7.27/28, I would have said that it may be the newly added assertions in `runCoreTask`, but since it's just a patched version of 0.7.26... 

But I have no idea how it could relate to this PR, except maybe that it changes the timing (connecting is slightly slower due to the additional `bind` call). Did you get the assertion message, or did it terminate before printing it?

**Comment by japplegame** [comment]
No! It was patched 0.7.**28** not 0.7.**26**.
Unfortunately 0.7.26 with this PR doesn't work at all (Peer failed the certificate validation: 20).

**Comment by japplegame** [comment]
assertion message
```
Manually resuming task that is already scheduled to be resumed.
```
Source: https://github.com/rejectedsoftware/vibe.d/blob/v0.7.28/source/vibe/core/core.d#L1239

**Comment by japplegame** [comment]
Also I tried v.0.7.29.alpha.2 and got the same assertion.

**Comment by s-ludwig** [comment]
Ah okay, that makes more sense then. I can't fight the feeling that the assertion is unfortunately too strict in practice. It helped to catch some bugs, but it also caused a rather bad one (#1441) and in most situations it's actually harmless to redundantly schedule a task for resumption. I'll weaken the assertion condition to only catch the actually critical cases.

**Comment by s-ludwig** [comment]
Okay, you could try to add 621e34b into the patch and do another test run.

**Comment by japplegame** [comment]
Ok. Testing...

**Comment by japplegame** [comment]
Well done. It works very well.

**Comment by s-ludwig** [comment]
Good to know! If you should ever run into the limitation of maximum outgoing connections, we could add the more relaxed approach that Etienne linked to as an option (but for now I think the basic bind-before-connect approach is the better choice).

**Pull request merged**
