### PR TITLE
Treat invalid JSON as bad request in the rest interface

### PR DESCRIPTION
**Pull request by jacob-carlborg**
The first commit strips trailing whitespace.

### CODE REVIEW

**Comment by s-ludwig** [comment]
LGTM. Just waiting for the CI to finish.

**Comment by jacob-carlborg** [comment]
I tried adding a failing test but it looked liked it was not executed. I ran `dub test`. Is there a way I can add a test?

**Comment by jacob-carlborg** [comment]
I managed to add a test.

**Comment by s-ludwig** [comment]
Okay, thanks!

**Comment by jacob-carlborg** [comment]
Thanks 😃.

**Comment by s-ludwig** [comment]
Hm, just noticed this unsent message in an open tab (in case it's still useful): `dub test` only executes the tests of the shell "vibe-d" package. You'd need `dub test :web` or `dub test --combined` in this case.

**Comment by jacob-carlborg** [comment]
Yeah, I looked in `.travis.yml` to figure out what to run.

**Pull request merged**
