### PR TITLE
got vibe to compile against openssl 1.1.0

### PR DESCRIPTION
**Pull request by burner**
just a crude hack, but I think nothing is fundamentally wrong with it.

https://github.com/rejectedsoftware/vibe.d/issues/1758

### CODE REVIEW

**Comment by burner** [comment]
is there any way to see the openssl version

**Comment by s-ludwig** [comment]
There is `OpenSSL_version_num()` - hopefully available on all involved versions.

**Comment by burner** [comment]
I meant at link time. The tests seem to fail to link.

**Comment by burner** [comment]
libressl looks like an alternative, has anyone had a look at that one yet?
they wrote a new tls library (tls.h) https://github.com/daniloegea/libressl-tls-api-examples shows an example

**Comment by wilzbach** [comment]
> I meant at link time. The tests seem to fail to link.

@burner: if you want to build a hack on top of a hack, you could use a `preBuildsCommands` and utilize the output of:

```
readelf -d /usr/lib/libssl.so | grep SONAME | sed -E 's/.*libssl[.]so[.](.*)].*/\1/'
```

e.g. by storing it in a gitignored D file

**Comment by burner** [comment]
@wilzbach thanks I will try that

**Comment by s-ludwig** [comment]
I've pulled this now and embedded it into a `version (VibeUseOpenSSL11)` until a better option supported by DUB is available.

**Comment by s-ludwig** [comment]
Maybe this can be solved in a proper way by extending the libs field to support version specifications or similar. The actual version could also be reported through a mechanism analog to https://github.com/dlang/dub/issues/6.

BTW, @burner thanks a lot for having done the fiddling to get this working!

**Comment by burner** [comment]
@s-ludwig nice thanks

**Comment by MartinNowak** [comment]
> Maybe this can be solved in a proper way by extending the libs field to support version specifications or similar. The actual version could also be reported through a mechanism analog to dlang/dub#6.
> 
> BTW, @burner thanks a lot for having done the fiddling to get this working!

One supported way would be to let people choose different openssl dub versions, e.g. `1.1.5+1.0.2j` or `2.0.1+1.1.0f`. Unfortunately this is not automatic.
The libs field already does support versioned libraries, see the workaround in https://github.com/rejectedsoftware/vibe.d/issues/1748#issuecomment-297647832. Most ld versions do support this syntax by now.

**Comment by wilzbach** [comment]
Why not list the openssl library dynamically?
Dlang-requests does this: https://github.com/ikod/dlang-requests/issues/45#issuecomment-317208703

**Pull request closed without merging**
