### PR TITLE
[Libasync] ManualEvent - Fix Race Condition and Optimize Space Usage

### PR DESCRIPTION
**Pull request by etcimon**
The allocations were inconsistent with binary increments and were hard to debug. This fixes it.

### CODE REVIEW

**Comment by etcimon** [comment]
Finally found the issue. Race conditions caused connections to fail unexpectedly

**Comment by s-ludwig** [comment]
Are those `+1`/`-1` operations stil relevant, then? They look kind of strange in code (at least in those places), although they seem to be semantically correct.

**Comment by etcimon** [comment]
They were originally intended to start the offsets at 0 for s_eventWaiters, which allows it to occupy space in factors of 2 which optimizes the use of the array container. Other than that, it's not very relevant I guess.

**Comment by s-ludwig** [comment]
I'd just usually do such arithmetic within `generateID` and `recycleID`, so that it is close together in a central place. With only a single call to each function, it doesn't matter that much in this case, but usually the current form would be relatively error prone.

**Comment by s-ludwig** [comment]
BTW, there is a `nothrow` related compilation error on Travis.

**Comment by s-ludwig** [comment]
Looks good!

**Pull request merged**
