### PR TITLE
Added missing mappings to registerRestInterface

### PR DESCRIPTION
**Pull request by chalucha**
Guess this was missing in the docs

### CODE REVIEW

**Comment by Geod24** [comment]
Looks like your fork is *a bit* too old ;)
You'd also have to format it using DDOC: https://github.com/rejectedsoftware/vibe.d/blob/5f851c723522dbc410641b2321ad0ad8f6dc7a76/source/vibe/web/rest.d#L36-L47

**Comment by chalucha** [comment]
Lol, didn't notice it :)
Hope it's better now

**Comment by Geod24** [comment]
LGTM

**Comment by s-ludwig** [comment]
Just one note w.r.t git: When updating a PR for the latest master, always try to use `git pull --rebase` to avoid the merge commit.  For an outdated branch, doing just `git pull` will really make the whole history difficult to read. Can you try that now, I hope that it will remove the existing merge commit. If it doesn't, I'll just cherry pick instead of merging.

**Comment by Geod24** [comment]
Oh I didn't see the merge commit.

`git pull --rebase` is a good thing, though I usually `git pull --ff-only upstream master master` and then `git rebase master` and fix the conflicts, if any.

**Comment by chalucha** [comment]
i've created better PR #1187
usually using SVN so git is sometimes too much ;-)

**Pull request closed without merging**
