### PR TITLE
[WIP] Test libevent, libev and libasync drivers

### PR DESCRIPTION
**Pull request by Geod24**
Test all the drivers on all supported compiler.
The downside of this is that it requires 18 jobs: https://travis-ci.org/Geod24/vibe.d

It would however need a dub improvement: https://github.com/D-Programming-Language/dub/issues/520

### CODE REVIEW

**Comment by s-ludwig** [comment]
I'd say we should just run `dub test` with each config for now. Compiling all examples seems like overkill. The external tests would fail for libev, so we should exclude at least those for that configuration.

**Comment by Geod24** [comment]
On the long run, I think we should just compile the examples with one config, to make sure they are up to date.
We also need way more tests. I'd do the REST part (I already have something, just need to clean it up and make sure it covers everything, but given my current workload that won't happen before 2 weeks).

**Comment by Geod24** [comment]
I edited it to only test it. Should be good to go.

**Comment by s-ludwig** [comment]
OK, I'll have a look at the libev driver.

**Comment by s-ludwig** [comment]
Nevermind ;)

**Pull request merged**
