### PR TITLE
Update dub.json

### PR DESCRIPTION
**Pull request by etcimon**
Try to go green

### CODE REVIEW

**Comment by s-ludwig** [comment]
Starting to look good. Glad I didn't put more work into debugging this on 0.7.1. I really should get libasync better integrated into my development workflow.

**Comment by etcimon** [comment]
Yes, you should also know that I've fixed a bunch of driver issues too on the http2-botan branch.

**Comment by etcimon** [comment]
Also, I refactored the client/server a lot, and found some case sensitive header comparisons (e.g. for content-encoding, == "gzip")

**Comment by s-ludwig** [comment]
Okay, good to know. My plan is to move things bit by bit into master anyway, so these are good candidates.

**Pull request merged**
