### PR TITLE
[post-0.7.24] Fix runWorkerTaskH when called outside of a task.

### PR DESCRIPTION
**Pull request by s-ludwig**
This fix has revealed some issues in the libev and libasync back ends and needs to be postponed to the next release.

### CODE REVIEW

**Comment by etcimon** [comment]
I tried to reproduce this but I'm getting linker errors for libasync on windows.. might need one last patch

**Comment by etcimon** [comment]
Hm I tried fixing this and it's going to take a little time. I'll check back on it later.

**Comment by s-ludwig** [comment]
Do you have a rough idea of what goes wrong/needs to be changed? I'd like to include this on master and either fix the failing drivers, or add assertions/skip tests for them.

**Comment by etcimon** [comment]
Last I checked I stopped at the thought that it's a `runWorkerTaskH` ambuiguity in the recursion (after fixing the driver error). I think it's that template parameter inference causing issues the way they're nested.

**Comment by s-ludwig** [comment]
Tests finally pass now after fixing the libev driver. The libasync issue seems to have gone, too.

(the failure is just due to a Travis internal issue)

**Pull request merged**
