### PR TITLE
Provide port information when the HTTP request isn't on the default port

### PR DESCRIPTION
**Pull request by Geod24**
Fixes rejectedsoftware/vibe.d#1507

### CODE REVIEW

**Comment by Geod24** [comment]
@s-ludwig : This will create another allocation when the port is provided.
I am **not so** fan of it (this kind of allocation could be avoided), although currently there are many places which use `~` so its in line with current practice.
Since you're doing a major refacto, do you have some plan for those ?

**Comment by etcimon** [comment]
Maybe lazy loading these headers only when the user calls req.headers, because otherwise I don't see how it's necessary to preload the container when you can get away with writing them to the stream directly when time comes.

**Comment by Geod24** [comment]
@s-ludwig : Ping

**Comment by s-ludwig** [comment]
A simple solution for the current architecture would be to allocate the buffer on the stack, within `requestHTTP`. I'm planning to add an allocation-less lower layer for the HTTP implementation, which would consist of some kind of callback based system that can be used to write headers directly to the wire. This would be the obvious candidate for a revised version.

BTW, what do you think about https://github.com/dlang/dub/pull/866?

**Comment by Geod24** [comment]
Thanks !

> I'm planning to add an allocation-less lower layer for the HTTP implementation, which would consist of some kind of callback based system that can be used to write headers directly to the wire. This would be the obvious candidate for a revised version.

That sounds very promising. Feel free to ping me when you have something ready.

> BTW, what do you think about dlang/dub#866?

Sorry for the late answer. Since I'm subscribed to many thing dlang wise, I may miss some of the notifications.

**Pull request merged**
