### PR TITLE
add sqlite mime-type

### PR DESCRIPTION
**Pull request by UplinkCoder**

### CODE REVIEW

**Comment by s-ludwig** [comment]
I was a little worried about the uniqueness of the file extension "db", but I guess it's today by far most popular for sqlite databases and it will have a small impact anyway. However, what about adding "s3db" to that list, it is mentioned quite frequently on the internet.

**Comment by UplinkCoder** [comment]
good idea

**Comment by UplinkCoder** [comment]
@s-ludwig done

**Comment by s-ludwig** [comment]
Thanks, merging.

**Pull request merged**
