### PR TITLE
[REST] Reorganize error handling + fix issue #949

### PR DESCRIPTION
**Pull request by Geod24**
A common problem I was encountering with REST was how painful it was to test failing cases (as the module should warn on interfaces error), as well as the duplication of code to have error both in client and server.
This centralize the error checking in a single CTFE function that is called from 2 static asserts. If the function returns non-null, it means there is an error (and the return is the error message).
Hence, it makes it quite easy to test issues, such as #949 which I originally intended to fix when I started this branch.

Note that `static assert (ParamNames[i].length, ..)` could never be false, as `std.traits.ParameterIdentifierTuple` would not compile (unless this has to do with an older release?). I fixed the test.
EDIT: Actually, this static assert now works in 2.067.

### CODE REVIEW

**Comment by s-ludwig** [comment]
Interesting idea with the `string` return. I just think it looks a bit too clever like this. I'd at least change the name to something like `getInterfaceValidationError`, because reading `static assert(!validateInterface!(I), validateInterface!(I));` had a slight WTF moment ;)

Maybe returning a small struct or tuple would be even cleaner (with the potential to safe one CTFE run), but the name change enough would be clean enough for me for an internal function.

**Comment by Geod24** [comment]
> Interesting idea with the string return. I just think it looks a bit too clever like this. I'd at least change the name to something like getInterfaceValidationError, because reading static assert(!validateInterface!(I), validateInterface!(I)); had a slight WTF moment ;)
>
> Maybe returning a small struct or tuple would be even cleaner (with the potential to safe one CTFE run), but the name change enough would be clean enough for me for an internal function.

It started as a template with a `static assert` inside it... But returning a message helps alot (because `__traits(compiles, ...)` is an awful way to check for correctness). And it needs to be a function because, well, CTFE and template are rarely compatible.

I changed the name, and add `is null` for extra verbosity. You're right, `getInterfaceValidationError` is much more suited as a name :)

**Comment by Geod24** [comment]
Ping

**Comment by s-ludwig** [comment]
Okay, looks good. It's definitely an interesting idiom.

Just out of interest, why did you need `__traits(compiles)` with the template+`static assert` solution, but not for the CTFE string return version?

**Comment by Geod24** [comment]
For testing.
If you put the assert directly inside the template, then how do you test that the generator correctly rejects invalid interface ? You're bound to use `__traits(compiles)`, and that's an horrible solution because if it breaks for a different reason, the test will pass.
Check line ~1200 for an example.

Note that my first attempt was to write an external test, but those should usually be 'black box' testing, so it required me to duplicate every single test (1 for client and 1 for server).

**Comment by s-ludwig** [comment]
Okay, makes sense.

**Pull request merged**
