### PR TITLE
don't split log lines on LF

### PR DESCRIPTION
**Pull request by MartinNowak**
- it might make sense to have newlines in a log message
  (e.g. when printing a backtrace) and they shouldn't
  be split into multiple log messages, e.g. when using syslog
- the splitting was poorly done anyhow (only on the first LF)

### CODE REVIEW

**Comment by s-ludwig** [comment]
I'd like to make this change optional - for example by adding a `@property bool multilineLogger` to `Logger`, which defaults to return `false`. Especially the HTML logger wouldn't work well with multiple lines per "line", as well as a custom logger that I have in an external code base (I could of course easily adapt it, but maybe there are more `Logger`s in the wild).

Interesting that the bug with splitting only at the first line separator slipped through so long. I never noticed that in the log output.

**Comment by MartinNowak** [comment]
made it configurable

**Comment by s-ludwig** [comment]
Okay, thanks! Also for fixing the line splitting along the way. The only issue seems to be that `splitter().front` is called unconditionally and fails for empty input strings.

**Comment by MartinNowak** [comment]
Fixed.
I didn't care about splitting on CR and what not.

**Comment by s-ludwig** [comment]
Yeah, I think it's completely OK to require the user to use UNIX line endings here. LGTM.

**Pull request merged**
