### PR TITLE
Fix license issues

### PR DESCRIPTION
**Pull request by etcimon**
The BSD license is restored on top of the code related to cookies in a separate file for now. This complex date parsing was necessary to receive cookies from twitter in my tests, where `* Apr-16 *` couldn't parse otherwise

### CODE REVIEW

**Comment by s-ludwig** [comment]
Needs a rebase.

**Comment by etcimon** [comment]
> Needs a rebase.

Mind if I commit on top of http2-botan-cleanup instead?

**Comment by s-ludwig** [comment]
It would be better to keep it here, because I'm constantly rewriting history in the cleanup branch.

**Comment by s-ludwig** [comment]
BTW, I mean rebase on top of rejectedsoftware:http2-botan and not onto :master

**Comment by etcimon** [comment]
> BTW, I mean rebase on top of rejectedsoftware:http2-botan and not onto :master

Might take some time, I get a bunch of conflicts not sure why

**Comment by s-ludwig** [comment]
If rebase doesn't work, can't you just reset your http2-botan branch to the one here and then paste the copyright notices back in? Or did you do some other modifications on your branch in the meantime?

**Comment by etcimon** [comment]
Yes, I can do that. I'm just not at the desk right now it might have to wait a few hours

**Comment by s-ludwig** [comment]
No problem, I'll have go to sleep now anyway :)

**Pull request merged**
