### PR TITLE
Fix wrong request time in access log when the connection is dropped

### PR DESCRIPTION
**Pull request by marcioapm**

### CODE REVIEW

**Comment by s-ludwig** [comment]
I wonder if we don't have a larger issue here. Not calling `finalize()` not only means that the request time isn't properly recorded, but also that we potentially leak resources. Do you have an exact reproduction recipe for this?

**Comment by marcioapm** [comment]
I believe it's happening mostly when refreshing while loading.
If you have a route that takes slightly longer to serve, press refresh a few times, not letting it finish and it should reproduce.

**Comment by s-ludwig** [comment]
Okay, I reproduced it and now `finalize()` is simply always called. I've added some checks to avoid additional log noise/exceptions.

**Comment by marcioapm** [comment]
Good stuff! Thanks! :)

**Pull request closed without merging**
