### PR TITLE
Fix libev build

### PR DESCRIPTION
**Pull request by Geod24**
Depends on https://github.com/D-Programming-Deimos/libev/pull/10 (and you making a new tag ;) ).

### CODE REVIEW

**Comment by s-ludwig** [comment]
Updated with 4.0.1 tag, still waiting for code.dlang.org to update. Once it is updated, can you bump the version number in dub.json?

**Comment by s-ludwig** [comment]
Wait a minute.. It'll have to be 5.0.0 due to the changed callback function signatures. I'll change that.

**Comment by s-ludwig** [comment]
OK, 5.0.0 is up.

**Comment by Geod24** [comment]
Should be good to go.

**Comment by Geod24** [comment]
I had to come up with some hacks to get a satisfying solution.
Since Travis requires you to disable `sudo` to use their docker-based infrastructure (which is much faster), we're downloading `libev` and compiling it in place (only adds about 8s of overhead per build).
I'm not aware of a way to provide lflags to dub, is there one ? I tried `LFLAGS="..." dub test ...`, looks like it's not supported.

**Comment by s-ludwig** [comment]
`LFLAGS` isn't supported, but it could be done with `DFLAGS` and `-Llinkerflag` (for DMD). You just need to also specify the other flags explicitly (`-g -debug`).

**Comment by s-ludwig** [comment]
I'll merge as is for now, the `LFLAGS`issue can be resolved later (I'd do it when I get some time later today).

**Comment by Geod24** [comment]
I tried this approach, it doesn't appear to work either, but I didn't had
time to investigate. Maybe related to
https://github.com/D-Programming-Language/dub/issues/500 .

2015-02-25 10:29 GMT+01:00 Sönke Ludwig <notifications@github.com>:

**Comment by s-ludwig** [comment]
You are probably right, forgot about that.

**Pull request merged**
