### PR TITLE
Remove explicit thread destruction code in the libasync driver.

### PR DESCRIPTION
**Pull request by s-ludwig**
See the discussion in #1835. Libasync now uses the default thread pool of `std.parallelism`, which is shut down automatically.

### CODE REVIEW

**Comment by wilzbach** [comment]
Wow that was a quick resolution - could you maybe release a new tag, s.t. these changes are propagated to the Project-Tester? Thanks!

**Comment by s-ludwig** [comment]
Let's wait with this until #1838 is merged, too.

**Comment by s-ludwig** [comment]
0.8.1-alpha.1 is now tagged and also available on code.dlang.org.

**Comment by wilzbach** [comment]
> 0.8.1-alpha.1 is now tagged and also available on code.dlang.org.

Thanks a lot. I will try to keep an eye on the Project-Tester to check whether this solved our problems.

**Pull request merged**
