### PR TITLE
Exit event loop in libasync using a signal

### PR DESCRIPTION
**Pull request by etcimon**

### CODE REVIEW

**Comment by s-ludwig** [comment]
I've taken a closer look and the issue is with the unit test in `vibe.core.sync`, line 303 ff.

`t1` hangs in `sleep(20.msecs);` indefinitely, so that `t1.join()` never returns either.

**Comment by etcimon** [comment]
Yes, the timer isn't being rescheduled because of a mistake I made in the driver. I'm testing it some more submitting a pull request.

**Comment by etcimon** [comment]
Seems like it was a pretty serious issue

**Comment by s-ludwig** [comment]
Looks nasty. Good to have this resolved!

**Pull request merged**
