### PR TITLE
Support client HTTPS requests via proxy HTTP tunnel.

### PR DESCRIPTION
**Pull request by japplegame**
Establishes HTTP tunnel before performing HTTPS requests.

### CODE REVIEW

**Comment by s-ludwig** [comment]
Sorry for the delay. My worry here is #1160. Apart from a lot of other things it also fixes this. I need to review that and decide on an approach and then see how to merge/rebase.

**Comment by etcimon** [comment]
https://github.com/etcimon/vibe.d/blob/master/source/vibe/http/client.d#L403

Implemented on my fork if interested, I needed this not too long ago

**Comment by japplegame** [comment]
I just accidentally messed up with git rebase. And recreated my fork :)

**Comment by etcimon** [comment]
What do you mean?

**Comment by etcimon** [comment]
I have about 200 commits on top of 300 commits behind master, don't try to rebase on it lol

**Pull request closed without merging**
