### PR TITLE
Fix validateEmail/isEmail inconsistency

### PR DESCRIPTION
**Pull request by radcapricorn**
Proposed fix for [issue 1580](https://github.com/rejectedsoftware/vibe.d/issues/1580).

### CODE REVIEW

**Comment by s-ludwig** [comment]
Interesting, so do I understand it right that `isEmail` has actually never worked at all? In that case, the affected `if` statement should be wrapped inside `static if (__VERSION__ >= 2072)`, so that the validation function does at least something useful for the released compiler versions.

**Comment by radcapricorn** [comment]
I'm not sure about "never", perhaps it's just not that widely used so it went unnoticed for a long time. I've added the version check.

**Comment by s-ludwig** [comment]
Okay, with "never" I meant something like at least since 2.064 or so, or since vibe.d started to use it.

I've moved the `static if` to outside of the `if`\*, so that the whole `isEmail` check is skipped on older DMD versions (doesn't make sense anyway). The basic checks are still performed, so it isn't that bad. The 2.072.0-b1 build presumably will still fail, but I'll fix that after merging this.

\* Just used the new PR edit feature for the first time. Definitely a lot nicer/more efficient than requesting the PR author to change small bits here and there.

**Comment by radcapricorn** [comment]
Thanks!

**Pull request merged**
