### PR TITLE
Update WebSocket sample

### PR DESCRIPTION
**Pull request by WilliamDunne**
Previous code didn't work as intended, and was also a strange way of writing it. Easier to put directly in while conditions

### CODE REVIEW

**Comment by s-ludwig** [comment]
Can you detail what didn't work in the old code? Looking at the code I believe that the reason for writing it that way was to handle the case where the WebSocket gets closed during the `sleep` call. With the condition in the `while` header, that would result in an exception being thrown now.

**Comment by MrDunne** [comment]
That didn't work in its entirety - regardless of how I closed the websocket it wasn't actually closing itself. Similarly, I didn't see any errors when closing it with the changes - I tested a couple of times and I can't imagine much time is spent in the rest of the loop.

**Comment by dariusc93** [comment]
During my test of the websocket example, it always close for me. Could you provide some code of your own to show that it isnt closing exactly as it is written in the code?

**Comment by s-ludwig** [comment]
Closing for now. The existing code looks like it should be correct. Would be interesting to determine why it failed.

**Pull request closed without merging**
