### PR TITLE
Libasync (linux) - Make sure TCP write ready events always occur

### PR DESCRIPTION
**Pull request by etcimon**

### CODE REVIEW

**Comment by etcimon** [comment]
This is a pretty bad bug actually, the protocol freezes when write blocks. Should be merged urgently.

**Comment by etcimon** [comment]
Tested in production as well

**Comment by s-ludwig** [comment]
I didn't merge this earlier because I didn't understand why a write operation would depend on a "read ready" event. Do you have any further insights on this? Anyway, this is safe to merge, so I'll include it in the release.

**Comment by etcimon** [comment]
I also have an issue understanding why I was blocking on write and receiving only a read event

**Pull request merged**
