### PR TITLE
Fix infinite connection attempt

### PR DESCRIPTION
**Pull request by etcimon**
The connectTCP function was returning correctly even though the connection attempt had failed.

### CODE REVIEW

**Comment by s-ludwig** [comment]
Seems like the change in log.d slipped in. Not sure if that workaround is safe to remove now (DMD 2.065).

**Comment by etcimon** [comment]
The writeln in core.d? Yes I'll remove that. It took me hours to find why I coudn't run my application with `/SUBSYSTEM:WINDOWS`, turns out writeln is going to throw an invalid descriptor exception in std.stdio and `Throwable.toString` refuses to attach a stack trace to it

**Comment by s-ludwig** [comment]
Okay, I suspected that when reading this... it's been a while since I last tested a `/SUBSYSTEM:WINDOWS` app (using console during development). Can you check if `write()` instead of `write("")` also fixes the issue? The idea is just to access anything from `std.stdio` to cause it to get initialized.

**Comment by etcimon** [comment]
Yes I can try that, the error came from LockingTextWriter actually

**Comment by s-ludwig** [comment]
I've tried now and even with the `write("");` I don't get an error for pure GUI applications. On which OS exactly did you have the error? Do you still get it now with the `write` call?

**Comment by s-ludwig** [comment]
Or maybe this was fixed in Phobos in the meantime?

**Comment by etcimon** [comment]
I got it with 2.068 on windows, using /SUBSYSTEM:WINDOWS in the lflags. I got around it by removing this enforcement: https://github.com/D-Programming-Language/phobos/blob/d9f44820953e33315712b08a7cf3fd5c49b3064b/std/stdio.d#L2377

And using `if (fp !is null)` here: https://github.com/D-Programming-Language/phobos/blob/d9f44820953e33315712b08a7cf3fd5c49b3064b/std/stdio.d#L197

**Comment by s-ludwig** [comment]
I just can't reproduce it at all (Using DMD 2.068/32-bit)... hm.. did you maybe use the VisualC++ runtime instead of the DigitalMars one (COFF)?

**Comment by etcimon** [comment]
> I just can't reproduce it at all (Using DMD 2.068/32-bit)... hm.. did you maybe use the VisualC++ runtime instead of the DigitalMars one (COFF)?

AH yes, I'm building with COFF on x86_64

**Comment by s-ludwig** [comment]
Okay, I'll try with that then.

**Comment by etcimon** [comment]
My application is a combined installer/service/launcher, it first evaluates if it has admin rights - if not it elevates, then it checks if the webserver is on - if not it checks if the service is installed - if not it installs a service otherwise runs it, then it launches a browser. I might release it once I have the launchd Mac version running, there's a new objective-c wrapper which is not currently merged here:  http://diveframework.com/

**Comment by s-ludwig** [comment]
Using `File f; f.close();` as a dummy operation instead of `write("");` fixed it. Can you rebase and remove the change here?

So your application would be useful as a generic management tool for server style applications? Sounds like it could be useful for things like vibelog or similar, too, at least for GUI-affine users. I didn't know about the Dive framework, it sounds great to have. But I was really waiting for someone to finally merge https://github.com/D-Programming-Language/dmd/pull/4321

**Comment by etcimon** [comment]
> I didn't know about the Dive framework, it sounds great to have. But I was really waiting for someone to finally merge D-Programming-Language/dmd#4321

Well, the dive framework was developed in association with the objective C attributes in that pull.

> So your application would be useful as a generic management tool for server style applications? Sounds like it could be useful for things like vibelog or similar, too, at least for GUI-affine users. 

It's really just a new branch of desktop applications. At least anything you'd do with Qt will be do-able with vibe.d, with the help of javascript user interfaces. Why learn Qml or embed a browser in a Window when you can interface with a client-side server? 

It would seem to have a promising future to me at the very least. Everyone knows javascript, so there's no learning curve, so instantly you've destroyed the "learning curve" argument against D.

**Comment by etcimon** [comment]
> Using File f; f.close(); as a dummy operation instead of write(""); fixed it. Can you rebase and remove the change here?

yep

**Comment by s-ludwig** [comment]
Thanks!

**Comment by etcimon** [comment]
Hmm, can you remove the `processTimers` in `TCPConnection.waitForData`? It is called from within a fiber and I got a few errors on my fork with it

**Comment by s-ludwig** [comment]
Done.

**Pull request merged**
