### PR TITLE
Test with ldc-0.15.2-beta2

### PR DESCRIPTION
**Pull request by Geod24**
Another "let's test and report regression" P.R.

### CODE REVIEW

**Comment by Geod24** [comment]
@klickverbot : I get the following from Travis:
```console
$ ldc2 --version
ldc2: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by ldc2)
```

Any idea ?

**Comment by redstar** [comment]
The problem is that I did not link against static libstdc++.so. Don't know how this happened. I'll create a new binary.

**Comment by redstar** [comment]
I still build with Ubuntu 12.04. But somehow I did lost the build script with the `-static-libstc++` switch. (It was not properly integrated so I did not commit the change.)

**Comment by Geod24** [comment]
@redstar : Any chance to get another beta which works with Travis ?

**Comment by Extrawurst** [comment]
Yeah a beta that works with Travis is much more likely to get test coverage

**Comment by redstar** [comment]
I rebuild the Linux binaries. They should work now in Travis-CI.

**Comment by Geod24** [comment]
@redstar : Am I doing something really stupid here ? Because I just retried and got the same error (see below). The hash correspond to the one you posted recently on the NG.

```console
geod24@barsoom2 ~ % md5sum ldc2-0.15.2-beta2-linux-x86_64.tar.xz 
18e4d0aec88ebbc58365bdc67b15cc7c  ldc2-0.15.2-beta2-linux-x86_64.tar.xz
geod24@barsoom2 ~ % tar -xf ldc2-0.15.2-beta2-linux-x86_64.tar.xz 
geod24@barsoom2 ~/ldc2-0.15.2-beta2-linux-x86_64 % ldd bin/ldc2
	linux-vdso.so.1 (0x00007ffca7123000)
	libconfig.so.8 => /home/geod24/ldc2-0.15.2-beta2-linux-x86_64/bin/libconfig.so.8 (0x00007f1b310e6000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f1b30ec9000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f1b30cc5000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f1b30943000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f1b3063f000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f1b30429000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f1b30087000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1b312f0000)
geod24@barsoom2 ~/ldc2-0.15.2-beta2-linux-x86_64 % md5sum ./bin/ldc2
e8f648ebdaeb7ed8274e419fb0597f28  ./bin/ldc2
```

**Comment by redstar** [comment]
Hm. The binary in my build does not depend on libstdc++, but the binary in archive does. I need to check the build scripts again.

**Comment by s-ludwig** [comment]
The LDC 0.15.2 release has been abandoned, I've opened #1289 to test 0.16.0-beta1.

**Pull request closed without merging**
