### PR TITLE
Vibe.internal.meta.codegen fixes

### PR DESCRIPTION
**Pull request by Geod24**
- Fixed ParameterTuple to have a saner API and take default parameters of different types, and even functions! But you won't be able to access it :-(
- Added CloneFunctionDecl, which clones a declaration (think CloneFunction without body).
- Added ability to CloneFunction to clone UDAs as well.

### CODE REVIEW

**Comment by Geod24** [comment]
@s-ludwig : Anything holding this back ?

**Comment by s-ludwig** [comment]
Sorry, just me being held back by other things. But apart from the `CloneFunction` question, LGTM (as well as #1048).

**Comment by Geod24** [comment]
> Is there any reason why `CloneFunction` does not use `CloneFunctionDecl` internally?

If you're thinking about factoring out the string generation and just adding the semicolon / body, I'd rather not do that: it's unlikely that those will change in the future, and if they do, they're close enough and trivial enough to make changes straightforward, and errors easy to spot.

Or do you have an idea to implement that using the function type ?

**Comment by s-ludwig** [comment]
Sounds reasonable, they're short enough. Merging.

**Comment by Geod24** [comment]
Thanks ! :)

**Pull request merged**
