### PR TITLE
Fixed build error in release mode

### PR DESCRIPTION
**Pull request by machindertech**

### CODE REVIEW

**Comment by Geod24** [comment]
The autotester's not too happy about it. What was the issue in release ?

**Comment by s-ludwig** [comment]
Yes, the error message would be interesting, as well as possibly a test case that can be added to the Travis-CI script. It currently calls `dub build -b release --combined`, but maybe that template doesn't get instantiated.

**Comment by machindertech** [comment]
We were getting the following error when building our project in 64-bit release mode on Linux:
../../dub/vibe.d/source/vibe/internal/meta/traits.d(153,31): Error: variable t used before set

**Comment by s-ludwig** [comment]
Wow, February, this got totally lost. I see no issue in merging this. Will be in 0.7.30.

**Pull request merged**
