### PR TITLE
Remove vibe-d:diet.

### PR DESCRIPTION
**Pull request by s-ludwig**
Should ideally have been removed together with 0.8.0 already. There is no reason anymore to rely on the old code rather than diet-ng.

See also #1834.

### CODE REVIEW

**Comment by wilzbach** [comment]
The same spurious failure that we could observe on the Project-Tester, seems to manifest itself here:

```
2017-07-12T11:42:16.157:threads.d:destroyAsyncThreads:34 Failed to terminate worker threads: core.thread.ThreadException@src/core/thread.d(773): Unable to join thread
----------------
??:? object.Throwable core.thread.Thread.join(bool) [0xc6c9f6]
??:? @trusted void std.parallelism.TaskPool.finish(bool) [0xc41abe]
../../../.dub/packages/libasync-0.8.3/libasync/source/libasync/threads.d:32 nothrow void libasync.threads.destroyAsyncThreads() [0xbc0e6b]
core/vibe/core/drivers/libasync.d:141 @trusted void vibe.core.drivers.libasync.LibasyncDriver.dispose() [0xb12e94]
core/vibe/core/driver.d:48 void vibe.core.driver.deleteEventDriver() [0xb12835]
core/vibe/core/core.d:1796 void vibe.core.core._staticDtor37() [0xafc182]
??:? void vibe.core.core.__moddtor() [0xb12650]
??:? void rt.minfo.__T17runModuleFuncsRevS482rt5minfo11ModuleGroup11runTlsDtorsMFZ9__lambda1Z.runModuleFuncsRev(const(immutable(object.ModuleInfo)*)[]) [0xc7b574]
??:? void rt.minfo.ModuleGroup.runTlsDtors() [0xc7b268]
??:? int rt.minfo.rt_moduleTlsDtor().__foreachbody1(ref rt.sections_elf_shared.DSO) [0xc247ab]
??:? int rt.sections_elf_shared.DSO.opApplyReverse(scope int delegate(ref rt.sections_elf_shared.DSO)) [0xc24b10]
??:? rt_moduleTlsDtor [0xc24794]
??:? thread_entryPoint [0xc6c81c]
??:? [0xebb9d183]
core.exception.AssertError@../../../.dub/packages/libasync-0.8.3/libasync/source/libasync/threads.d(35): Assertion failure
----------------2017-07-12T11:42:16.158:threads.d:destroyAsyncThreads:34 Failed to terminate worker threads: core.thread.ThreadException@src/core/thread.d(773): Unable to join thread
----------------
??:? object.Throwable core.thread.Thread.join(bool) [0xc6c9f6]
??:? @trusted void std.parallelism.TaskPool.finish(bool) [0xc41abe]
../../../.dub/packages/libasync-0.8.3/libasync/source/libasync/threads.d:32 nothrow void libasync.threads.destroyAsyncThreads() [0xbc0e6b]
core/vibe/core/drivers/libasync.d:141 @trusted void vibe.core.drivers.libasync.LibasyncDriver.dispose() [0xb12e94]
core/vibe/core/driver.d:48 void vibe.core.driver.deleteEventDriver() [0xb12835]
core/vibe/core/core.d:1796 void vibe.core.core._staticDtor37() [0xafc182]
??:? void vibe.core.core.__moddtor() [0xb12650]
??:? void rt.minfo.__T17runModuleFuncsRevS482rt5minfo11ModuleGroup11runTlsDtorsMFZ9__lambda1Z.runModuleFuncsRev(const(immutable(object.ModuleInfo)*)[]) [0xc7b574]
??:? void rt.minfo.ModuleGroup.runTlsDtors() [0xc7b268]
??:? int rt.minfo.rt_moduleTlsDtor().__foreachbody1(ref rt.sections_elf_shared.DSO) [0xc247ab]
??:? int rt.sections_elf_shared.DSO.opApplyReverse(scope int delegate(ref rt.sections_elf_shared.DSO)) [0xc24b10]
??:? rt_moduleTlsDtor [0xc24794]
??:? thread_entryPoint [0xc6c81c]
??:? [0xebb9d183]
```

**Comment by s-ludwig** [comment]
That sometimes happens, would be nice if the error code would be accessible somehow. But looking at the documentation of `pthread_join`, the two likely candidates are that either another thread already waits in `Thread.join` for the same thread, or that two threads try to join each other.

Shot in the dark: if those libasync threads are not daemon threads, Druntime might already try to join them.

**Comment by s-ludwig** [comment]
Also pinging @etcimon

**Comment by etcimon** [comment]
Looks like a new bug, I'd have to test with the newer versions for this. Maybe destroying these threads is unnecessary now

**Comment by s-ludwig** [comment]
AFAICS, this was a mistake in https://github.com/etcimon/libasync/commit/e22223559bed2cf0654f927d6fb0a4c9cc2e2fe9 - the default `taskPool` is set as a daemon and `std.parallelism` will shut down the threads automatically. I'll open a PR that removes the call to `destroyAsyncThreads` - I think that can just be deprecated and removed now.

**Pull request merged**
