### PR TITLE
Libasync ManualEvent in FileStream - fixes #1225

### LINKED ISSUE #1225: calling resumeTask from another task - libasync bug?
This may be a bug in libasync, not sure who to blame. When vibe.d's configuration is left as the default, everything runs fine.

```
Building memutils 0.4.1 configuration "secure", build type debug.
Running dmd...
Enhanced memory security is enabled.
Building libasync 0.7.5 configuration "regular", build type debug.
Running dmd...
Enhanced memory security is enabled.
Using Linux EPOLL for events
Building vibe-d 0.7.24 configuration "libasync", build type debug.
Running dmd...
Enhanced memory security is enabled.
Using Linux EPOLL for events
Building blog.abcdefghij ~master configuration "application", build type debug.
Compiling using dmd...
Enhanced memory security is enabled.
Using Linux EPOLL for events
Compiling diet template 'index.dt'...
Linking...
Running ./blog.abcdefghij 
Listening for HTTP requests on ::1:8080
Listening for HTTP requests on 127.0.0.1:8080
Please open http://127.0.0.1:8080/ in your browser.
core.exception.AssertError@../../../../../../.dub/packages/vibe-d-0.7.24/source/vibe/core/core.d(1083): Calling resumeTask from another task.
----------------
./blog.abcdefghij(void vibe.core.core.VibeDriverCore.resumeTask(vibe.core.task.Task, Exception)+0xca) [0x810d5e]
./blog.abcdefghij(void vibe.core.drivers.libasync.LibasyncFileStream.handler()+0xeb) [0x8173af]
./blog.abcdefghij(shared(void function()) libasync.file.FileReadyHandler.opCall+0x74) [0x954038]
./blog.abcdefghij(shared(nothrow bool function(immutable(char)[], shared(ubyte[]), ulong, bool, bool)) libasync.file.AsyncFile.read+0x3f1) [0x952b29]
./blog.abcdefghij(void vibe.core.drivers.libasync.LibasyncFileStream.read(ubyte[])+0x1b1) [0x81680d]
./blog.abcdefghij(void vibe.core.stream.OutputStream.writeDefault(vibe.core.stream.InputStream, ulong)+0x124) [0x82d054]
./blog.abcdefghij(void vibe.core.drivers.libasync.LibasyncTCPConnection.write(vibe.core.stream.InputStream, ulong)+0x88) [0x81a8d4]
./blog.abcdefghij(void vibe.http.server.HTTPServerResponse.writeRawBody(vibe.core.stream.RandomAccessStream)+0x10c) [0x858c38]
./blog.abcdefghij(void vibe.http.fileserver.sendFile(scope vibe.http.server.HTTPServerRequest, scope vibe.http.server.HTTPServerResponse, vibe.inet.path.Path, vibe.http.fileserver.HTTPFileServerSettings)+0xbc7) [0x8c7417]
./blog.abcdefghij(void vibe.http.fileserver.serveStaticFile(vibe.inet.path.Path, vibe.http.fileserver.HTTPFileServerSettings).callback(scope vibe.http.server.HTTPServerRequest, scope vibe.http.server.HTTPServerResponse)+0x39) [0x8c6709]
./blog.abcdefghij(_D4vibe4http6router9URLRouter13handleRequestMFC4vibe4http6server17HTTPServerRequestC4vibe4http6server18HTTPServerResponseZ21__T9__lambda3TmTAAyaZ9__lambda3MFmMAAyaZv+0x1fb) [0x854fff]
./blog.abcdefghij(const(void function(immutable(char)[], scope void delegate(ulong, scope immutable(char)[][]))) vibe.http.router.MatchTree!(vibe.http.router.Route).MatchTree.doMatch+0x196) [0x7da196]
./blog.abcdefghij(void vibe.http.router.MatchTree!(vibe.http.router.Route).MatchTree.match(immutable(char)[], scope void delegate(ulong, scope immutable(char)[][]))+0x93) [0x7d99fb]
./blog.abcdefghij(void vibe.http.router.URLRouter.handleRequest(vibe.http.server.HTTPServerRequest, vibe.http.server.HTTPServerResponse)+0x196) [0x854d9a]
./blog.abcdefghij(bool vibe.http.server.handleRequest(vibe.core.stream.Stream, vibe.core.net.TCPConnection, vibe.http.server.HTTPListenInfo, ref vibe.http.server.HTTPServerSettings, ref bool)+0x17d9) [0x8ca911]
./blog.abcdefghij(void vibe.http.server.handleHTTPConnection(vibe.core.net.TCPConnection, vibe.http.server.HTTPListenInfo)+0x1a3) [0x8c9033]
./blog.abcdefghij(void vibe.http.server.listenHTTPPlain(vibe.http.server.HTTPServerSettings).doListen(vibe.http.server.HTTPListenInfo, bool).__lambda3(vibe.core.net.TCPConnection)+0x36) [0x8c8a32]
./blog.abcdefghij(void vibe.core.drivers.libasync.LibasyncTCPConnection.onConnect()+0xa8) [0x81b7ec]
./blog.abcdefghij(void vibe.core.core.makeTaskFuncInfo!(void delegate()).makeTaskFuncInfo(ref void delegate()).callDelegate(vibe.core.core.TaskFuncInfo*)+0x72) [0x812036]
./blog.abcdefghij(void vibe.core.core.CoreTask.run()+0x129) [0x81001d]
./blog.abcdefghij(void core.thread.Fiber.run()+0x2a) [0x9c771e]
./blog.abcdefghij(fiber_entryPoint+0x61) [0x9c760d]
[(nil)]
Task terminated with unhandled exception: Calling resumeTask from another task.
core.exception.AssertError@../../../../../../.dub/packages/vibe-d-0.7.24/source/vibe/core/core.d(1083): Calling resumeTask from another task.
----------------
./blog.abcdefghij(void vibe.core.core.VibeDriverCore.resumeTask(vibe.core.task.Task, Exception)+0xca) [0x810d5e]
./blog.abcdefghij(void vibe.core.drivers.libasync.LibasyncFileStream.handler()+0xeb) [0x8173af]
./blog.abcdefghij(shared(void function()) libasync.file.FileReadyHandler.opCall+0x74) [0x954038]
./blog.abcdefghij(shared(nothrow bool function(immutable(char)[], shared(ubyte[]), ulong, bool, bool)) libasync.file.AsyncFile.read+0x3f1) [0x952b29]
./blog.abcdefghij(void vibe.core.drivers.libasync.LibasyncFileStream.read(ubyte[])+0x1b1) [0x81680d]
./blog.abcdefghij(void vibe.core.stream.OutputStream.writeDefault(vibe.core.stream.InputStream, ulong)+0x124) [0x82d054]
./blog.abcdefghij(void vibe.core.drivers.libasync.LibasyncTCPConnection.write(vibe.core.stream.InputStream, ulong)+0x88) [0x81a8d4]
./blog.abcdefghij(void vibe.http.server.HTTPServerResponse.writeRawBody(vibe.core.stream.RandomAccessStream)+0x10c) [0x858c38]
./blog.abcdefghij(void vibe.http.fileserver.sendFile(scope vibe.http.server.HTTPServerRequest, scope vibe.http.server.HTTPServerResponse, vibe.inet.path.Path, vibe.http.fileserver.HTTPFileServerSettings)+0xbc7) [0x8c7417]
./blog.abcdefghij(void vibe.http.fileserver.serveStaticFile(vibe.inet.path.Path, vibe.http.fileserver.HTTPFileServerSettings).callback(scope vibe.http.server.HTTPServerRequest, scope vibe.http.server.HTTPServerResponse)+0x39) [0x8c6709]
./blog.abcdefghij(_D4vibe4http6router9URLRouter13handleRequestMFC4vibe4http6server17HTTPServerRequestC4vibe4http6server18HTTPServerResponseZ21__T9__lambda3TmTAAyaZ9__lambda3MFmMAAyaZv+0x1fb) [0x854fff]
./blog.abcdefghij(const(void function(immutable(char)[], scope void delegate(ulong, scope immutable(char)[][]))) vibe.http.router.MatchTree!(vibe.http.router.Route).MatchTree.doMatch+0x196) [0x7da196]
./blog.abcdefghij(void vibe.http.router.MatchTree!(vibe.http.router.Route).MatchTree.match(immutable(char)[], scope void delegate(ulong, scope immutable(char)[][]))+0x93) [0x7d99fb]
./blog.abcdefghij(void vibe.http.router.URLRouter.handleRequest(vibe.http.server.HTTPServerRequest, vibe.http.server.HTTPServerResponse)+0x196) [0x854d9a]
./blog.abcdefghij(bool vibe.http.server.handleRequest(vibe.core.stream.Stream, vibe.core.net.TCPConnection, vibe.http.server.HTTPListenInfo, ref vibe.http.server.HTTPServerSettings, ref bool)+0x17d9) [0x8ca911]
./blog.abcdefghij(void vibe.http.server.handleHTTPConnection(vibe.core.net.TCPConnection, vibe.http.server.HTTPListenInfo)+0x1a3) [0x8c9033]
./blog.abcdefghij(void vibe.http.server.listenHTTPPlain(vibe.http.server.HTTPServerSettings).doListen(vibe.http.server.HTTPListenInfo, bool).__lambda3(vibe.core.net.TCPConnection)+0x36) [0x8c8a32]
./blog.abcdefghij(void vibe.core.drivers.libasync.LibasyncTCPConnection.onConnect()+0xa8) [0x81b7ec]
./blog.abcdefghij(void vibe.core.core.makeTaskFuncInfo!(void delegate()).makeTaskFuncInfo(ref void delegate()).callDelegate(vibe.core.core.TaskFuncInfo*)+0x72) [0x812036]
./blog.abcdefghij(void vibe.core.core.CoreTask.run()+0x129) [0x81001d]
./blog.abcdefghij(void core.thread.Fiber.run()+0x2a) [0x9c771e]
./blog.abcdefghij(fiber_entryPoint+0x61) [0x9c760d]
[(nil)]
Error executing command run:
Program exited with code 1
```

### PR DESCRIPTION
**Pull request by etcimon**
This should avoid the resumeTask issue, and with timeout for an added bonus

### CODE REVIEW

**Comment by s-ludwig** [comment]
Isn't `yieldAndResumeTask` the correct fix here? Using a `ManualEvent` sounds like redundant overhead, since everything is in a single thread anyway (right?). What would happen if the timeout gets hit?

**Comment by etcimon** [comment]
I recently made the read/write happen in the current thread when the buffer is < 65kb (through a libasync change). The mutex is not worth it for small reads. The task still registers itself in `m_task` at the scope start, which should be only if it waits through a boolean. I think I had a pull request for that previously.

So I guess this was a quick fix that worked in every situation and I didn't have time to break it down to a better `m_reader` and `m_writer` that get defined when the task starts waiting.

> What would happen if the timeout gets hit?

The intended result is that an exception is thrown and internal server error gets returned. The timeout would have to be proportional to the read size, but it reads small chunks 99.9% of the time. I'd rather see a TimeoutException for better error reports though.

**Comment by etcimon** [comment]
Hm I just remembered why I used a ManualEvent. The handler in the LibasyncFileStream gets called by a foreign thread in the thread pool, so the task would be resumed from a foreign thread.

**Comment by etcimon** [comment]
> , so the task would be resumed from a foreign thread.

I just checked and this was a wrong assumption . I had forgotten using AsyncSignal behind the scenes, so this would work correctly without ManualEvent

**Comment by etcimon** [comment]
It's already been almost 2 months. Been busy, I'll fix this tomorrow

**Comment by s-ludwig** [comment]
Still got build failures on < 2.069 (2.069 failure unrelated).

**Comment by etcimon** [comment]
Would you consider adding the ConnectionClosedException? They happen quite frequently and litter the logs if they're not caught separately

**Comment by s-ludwig** [comment]
Yes, sounds like a good addition. However, I'd probably postpone that to after the release, because all drivers should be adjusted accordingly.

**Comment by etcimon** [comment]
Out of context, but do you intent to add the new fastjson simd optimizations to your std.json library?

**Comment by s-ludwig** [comment]
Not directly, but in the long term that would definitely make sense and there is nothing that would preclude it. However, the library is GPL, so no code can be directly taken form there.

**Comment by etcimon** [comment]
I don't think json parsing would be my bottleneck anyways, so it's not worth concentrating efforts more than necessary. I think in the real world the only advantage is from having inlinine or parsing strings faster with `vpcmpistri`.

**Pull request merged**
