### PR TITLE
use parseRFC822DateTime from std.datetime

### PR DESCRIPTION
**Pull request by MartinNowak**
- available since 2.066

### CODE REVIEW

**Comment by MartinNowak** [comment]
[Issue 12886 – std.datetime cannot parse HTTP date](https://issues.dlang.org/show_bug.cgi?id=12886)

**Comment by Geod24** [comment]
Good catch. But what's up with the autotester and those frequent 404 ?

0.04scurl: (22) The requested URL returned error: 403
0.24s$ curl http://code.dlang.org/files/dub-${LATEST_DUB}-linux-x86_64.tar.gz | tar -C ~/dmd2/linux/bin64 -xzf -
curl: (22) The requested URL returned error: 404

Is it an issue on code.dlang.org's end ?

**Comment by MartinNowak** [comment]
> Is it an issue on code.dlang.org's end?

I think so, seen them a couple of times now.

**Comment by Geod24** [comment]
> I think so, seen them a couple of times now.

Maybe it would be good to have some redundancy on dlang.org then.
Also, you need to force push this to let Travis have another go at it.

**Comment by s-ludwig** [comment]
I'm getting sporadic segmentation faults since a while that I haven't looked into, yet. But that should produce a 500 error (well, actually it *should* produce a 502, but that's a different story) while the registry process is being restarted and not a 404, so I'm not completely sure if this is actually related.

I'll just merge for now and then will have a look at the reason for the crash.

**Comment by s-ludwig** [comment]
Turns out that `LATEST_DUB` is simply not defined and it tries to download `/files/dub--linux-x86_64.tar.gz`.

**Comment by MartinNowak** [comment]
Would be nice to somehow get the latest version from code.dlang.org.

**Pull request merged**
