### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by John-Colvin**
ran in to some problems myself with dmd 2.073.1, perhaps it'll show up here also.

### CODE REVIEW

**Comment by wilzbach** [comment]
@John-Colvin Vibe.d is one of the projects that are run by the Project Tester. This means that on every commit in DMD/Druntime/Phobos all these projects get run. However this setup is still in testing mode.

For more details:
https://ci.dawg.eu/job/projects/

**Comment by John-Colvin** [comment]
@wilzbach, that's good to know., 

Because Travis is so popular it seems important that vibe.d is tested in that environment. Also useful to test ldc. Also useful to check changes to vibe.d don't break compatibility with older compilers.

**Comment by s-ludwig** [comment]
I updated to 2.073.2 now on master and 0.7.0 and the tests all succeed. BTW, do the 2.073.1 issues still show up on 2.073.2? I think I had some issues, too, but I can't remember what those were and 2.073.2 appears to work flawlessly.

**Comment by wilzbach** [comment]
This seems to have been superseded by another PR. At least both, new compilers are in:
https://github.com/rejectedsoftware/vibe.d/blob/master/.travis.yml

@John-Colvin @s-ludwig can we close this?
Though it might be a good idea to use the `dmd`, `ldc` tags to avoid needing to continuously update the travis file, see e.g. https://github.com/rejectedsoftware/vibe.d/pull/1772

**Comment by John-Colvin** [comment]
Replaced with: https://github.com/rejectedsoftware/vibe.d/pull/1814

**Pull request closed without merging**
